package co.gov.corpocaldas.AccessLayerRequest.controller;

import co.gov.corpocaldas.AccessLayerRequest.dto.AccessRequestDto;
import co.gov.corpocaldas.AccessLayerRequest.dto.PaginatorDto;
import co.gov.corpocaldas.AccessLayerRequest.service.AccessRequestService;
import co.gov.corpocaldas.AccessLayerRequest.service.ValidateAccessService;
import io.swagger.annotations.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.mail.MessagingException;
import java.util.List;

@RestController
@RequestMapping("${api.base.url}/access-request")
@Api
public class AccessRequestController {

    private final AccessRequestService accessRequestService;

    private final ValidateAccessService validateAccessService;

    public AccessRequestController(AccessRequestService accessRequestService, ValidateAccessService validateAccessService) {
        this.accessRequestService = accessRequestService;
        this.validateAccessService = validateAccessService;
    }

    /**
     * Endpoint that persist the information of an access request.
     * @param accessRequest Information of access request
     * @return Response entity with the status and body generated by request
     */
    @ApiOperation(value = "Endpoint that persist the information of an access request", response = AccessRequestDto.class)
    @ApiResponses(value = {
            @ApiResponse(code = 201, message = "The information of access request was persisted successfully"),
            @ApiResponse(code = 400, message = "The information of access request is invalid ")
    })
    @PostMapping()
    public ResponseEntity<AccessRequestDto> saveRequestAccess(
            @ApiParam(value = "Information of access request", required = true) @RequestBody AccessRequestDto accessRequest) throws MessagingException {
        return new ResponseEntity<>(accessRequestService.saveRequestAccess(accessRequest), HttpStatus.CREATED);
    }

    /**
     * Endpoint that update the information of a specific access request.
     * @param accessRequestId Identifier of the access request
     * @param accessRequest Updated information of the access request
     * @return Response entity with the updated information of the access request
     */
    @ApiOperation(value = "Endpoint that update the information of a specific access request", response = AccessRequestDto.class)
    @ApiResponses(value = {
            @ApiResponse(code = 202, message = "The information of the access request was updated successfully"),
            @ApiResponse(code = 400, message = "The identifier provided by path param mismatch with the identifier that" +
                    " is inside the information or the information of access request is invalid")
    })
    @PutMapping("/{accessRequestId}")
    public ResponseEntity<AccessRequestDto> updateRequestAccess(
            @RequestHeader(value = "authorization-token", required = false) String token,
            @RequestHeader(value = "authorization-user", required = false) Integer userId,
            @ApiParam(value = "Identifier of the access request", required = true) @PathVariable("accessRequestId") int accessRequestId,
            @ApiParam(value = "Updated information of the access request", required = true) @RequestBody AccessRequestDto accessRequest) throws MessagingException {
        //validateAccessService.validateAccess(token, userId);
        return new ResponseEntity<>(accessRequestService.updateRequestAccess(accessRequestId, accessRequest), HttpStatus.ACCEPTED);
    }

    /**
     * Apply filter on access request by params selected.
     * @param name Name of the user that request the access
     * @param company Name of company or entity associated to request
     * @param email Email of the user that request the access
     * @param layername Layer name associated to request
     * @return Response entity with the access requests that matching with the parameters value
     */
    @ApiOperation(value = "Apply filter on access request by params selected", response = PaginatorDto.class)
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "The filter was applied on access request successfully")
    })
    @GetMapping()
    public ResponseEntity<PaginatorDto> filterAccessRequest(
            @RequestHeader(value = "authorization-token", required = false) String token,
            @RequestHeader(value = "authorization-user", required = false) Integer userId,
            @ApiParam(value = "Name of the user that request the access")
            @RequestParam(value = "name", required = false) String name,
            @ApiParam(value = "Name of company or entity associated to request")
            @RequestParam(value = "company", required = false) String company,
            @ApiParam(value = "Email of the user that request the access")
            @RequestParam(value = "email", required = false) String email,
            @ApiParam(value = "Layer name associated to request")
            @RequestParam(value = "layername", required = false) String layername,
            @ApiParam(value = "Layer access granted associated to request")
            @RequestParam(value = "access_granted", required = false) Integer layeraccessgranted,
            @ApiParam(value = "Page number", defaultValue = "0")
            @RequestParam(value = "page", defaultValue = "0") int page,
            @ApiParam(value = "Page size", defaultValue = "10")
            @RequestParam(value = "size", defaultValue = "10") int size) {
        //validateAccessService.validateAccess(token, userId);
        return new ResponseEntity<>(accessRequestService.filterAccessRequests(name, company, email, layername,
                layeraccessgranted, page, size), HttpStatus.OK);
    }

}
